module.exports = {
    foodSeed: [
        {
            sku: 'foodbakery_special_pizza',
            image: '/uploads/food/foodbakery_special_pizza.jpg',
            folder: 'foodbakery_special_pizza',
            qty: 12,
            categoryId: 'pizza',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'foodbakery_pizza',
            image: '/uploads/food/foodbakery_special_pizza.jpg',
            folder: 'foodbakery_pizza',
            qty: 5,
            categoryId: 'pizza',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'special_pizza',
            image: '/uploads/food/foodbakery_special_pizza.jpg',
            folder: 'special_pizza',
            qty: 12,
            categoryId: 'pizza',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'bakery_special_pizza',
            image: '/uploads/food/foodbakery_special_pizza.jpg',
            folder: 'bakery_special_pizza',
            qty: 12,
            categoryId: 'pizza',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'bakery_pizza',
            image: '/uploads/food/foodbakery_special_pizza.jpg',
            folder: 'bakery_pizza',
            qty: 5,
            categoryId: 'pizza',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'special_special_pizza',
            image: '/uploads/food/foodbakery_special_pizza.jpg',
            folder: 'special_special_pizza',
            qty: 12,
            categoryId: 'pizza',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'calzone_folded_pizza',
            image: '/uploads/food/calzone_folded_pizza.jpg',
            folder: 'calzone_folded_pizza',
            qty: 23,
            categoryId: 'calzone',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'garlic_pizza_pread_9_thin_crust',
            image: '/uploads/food/garlic_pizza_pread_9_thin_crust.jpg',
            folder: 'garlic_pizza_pread_9_thin_crust',
            qty: 34,
            categoryId: 'bread',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'yogurt_kebab',
            image: '/uploads/food/yogurt_kebab.jpg',
            folder: 'yogurt_kebab',
            qty: 12,
            categoryId: 'kebabs',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'cheese_burger',
            image: '/uploads/food/cheese_burger.jpg',
            folder: 'cheese_burger',
            qty: 12,
            categoryId: 'burgers',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'donner_meat',
            image: '/uploads/food/donner_meat.jpg',
            folder: 'donner_meat',
            qty: 12,
            categoryId: 'specials',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: 'chicken_wrap',
            image: '/uploads/food/chicken_wrap.jpg',
            folder: 'chicken_wrap',
            qty: 12,
            categoryId: 'wraps',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        }, {
            sku: '1_piece_of_chicken_meal',
            image: '/uploads/food/1_piece_of_chicken_meal.jpg',
            folder: '1_piece_of_chicken_meal',
            qty: 12,
            categoryId: 'chicken',
            vendorId: null,
            inSlider: false,
            isFeature: false,
            status: true,
            viewCount: 0,
            sellCount: 0,
        },
    ],
    foodTransSeed: [
        {
            title: 'Foodbakery Special Pizza',
            desc: 'Cheese, tomatoes, tuna fish, sweetcorn and italian herbs',
            price: 50,
            oldPrice: 70,
            abbr: 'EN',
            sku: 'foodbakery_special_pizza',
        }, {
            title: 'بيتزا فود باكيري الخاصة',
            desc: 'الجبن ، الطماطم ، سمك التونة ، الذرة الحلوة والأعشاب الإيطالية',
            price: 100,
            oldPrice: 140,
            abbr: 'AR',
            sku: 'foodbakery_special_pizza',
        }, {
            title: 'Foodbakery Pizza',
            desc: 'tuna fish, sweetcorn and italian herbs, Cheese, tomatoes, Cheese, tomatoes',
            price: 20,
            oldPrice: 70,
            abbr: 'EN',
            sku: 'foodbakery_pizza',
        }, {
            title: 'بيتزا فود باكيري ',
            desc: 'الجبن ، الطماطم ، سمك التونة ، الذرة الحلوة والأعشاب ',
            price: 60,
            oldPrice: 80,
            abbr: 'AR',
            sku: 'foodbakery_pizza',
        }, {
            title: 'Special Pizza',
            desc: 'sweetcorn and italian herbs, Cheese, tomatoes, tuna fish, Cheese, tomatoes, tuna fish',
            price: 30,
            oldPrice: 70,
            abbr: 'EN',
            sku: 'special_pizza',
        }, {
            title: 'بيتزا فود  ',
            desc: 'الجبن ، الطماطم ، سمك التونة ، الذرة الحلوة',
            price: 70,
            oldPrice: 90,
            abbr: 'AR',
            sku: 'special_pizza',
        }, {
            title: 'Bakery Special Pizza',
            desc: 'Cheese, tomatoes, tuna fish, sweetcorn and italian herbs',
            price: 50,
            oldPrice: 70,
            abbr: 'EN',
            sku: 'bakery_special_pizza',
        }, {
            title: 'بيتزا فود الطماطم',
            desc: 'لجبن ، الطماطم ، سمك الجبن ، الطماطم ، سمك التونة ، الذرة الحلوة',
            price: 90,
            oldPrice: 100,
            abbr: 'AR',
            sku: 'bakery_special_pizza',
        }, {
            title: 'bakery Pizza',
            desc: 'tuna fish, sweetcorn and italian herbs, Cheese, tomatoes, Cheese, tomatoes',
            price: 20,
            oldPrice: 70,
            abbr: 'EN',
            sku: 'bakery_pizza',
        }, {
            title: 'بيتزا فود الطماطالذرة الحلوم',
            desc: 'لجبن ، الطماطم ، سمك الجبن ، الطماطم ، سمك التونة ، الذرة الحلوة',
            price: 40,
            oldPrice: 50,
            abbr: 'AR',
            sku: 'bakery_pizza',
        }, {
            title: 'Special special Pizza',
            desc: 'sweetcorn and italian herbs, Cheese, tomatoes, tuna fish, Cheese, tomatoes, tuna fish',
            price: 30,
            oldPrice: 70,
            abbr: 'EN',
            sku: 'special_special_pizza',
        }, {
            title: 'بيتزا فود الطماطالذرة الحلومالحلوة',
            desc: 'لجبن ، الطماطم ، سمك الجبن ، الطماطم ، سمك التونة ، الذرة ',
            price: 50,
            oldPrice: 70,
            abbr: 'AR',
            sku: 'special_special_pizza',
        }, {
            title: 'Calzone (Folded Pizza)',
            desc: 'Cheese, tomatoes and italian herbs.',
            price: 70,
            oldPrice: 75,
            abbr: 'EN',
            sku: 'calzone_folded_pizza',
        }, {
            title: 'كالزون (بيتزا مطوية)',
            desc: 'الجبن والطماطم والأعشاب الإيطالية.',
            price: 140,
            oldPrice: 150,
            abbr: 'AR',
            sku: 'calzone_folded_pizza',
        }, {
            title: 'Garlic Pizza Bread 9 " Thin Crust',
            desc: 'Butter and crushed garlic, then spread a little over the pizza',
            price: 30,
            oldPrice: 30,
            abbr: 'EN',
            sku: 'garlic_pizza_pread_9_thin_crust',
        }, {
            title: 'خبز البيتزا بالثوم 9 "قشرة رقيقة',
            desc: 'الزبدة والثوم المسحوق ، ثم انتشر قليلاً على البيتزا',
            price: 60,
            oldPrice: 60,
            abbr: 'AR',
            sku: 'garlic_pizza_pread_9_thin_crust',
        }, {
            title: 'Yogurt Kebab',
            desc: 'Tomatoes, garlic, oregano, and extra virgin olive oil',
            price: 12.5,
            oldPrice: 12.5,
            abbr: 'EN',
            sku: 'yogurt_kebab',
        }, {
            title: 'كباب زبادي',
            desc: 'طماطم ، ثوم ، زعتر وزيت زيتون بكر',
            price: 25,
            oldPrice: 25,
            abbr: 'AR',
            sku: 'yogurt_kebab',
        }, {
            title: 'Cheese Burger',
            desc: 'Topped with pineapple and cheese',
            price: 20,
            oldPrice: 20,
            abbr: 'EN',
            sku: 'cheese_burger',
        }, {
            title: 'برجر بالجبنة',
            desc: 'يعلوها الأناناس والجبن',
            price: 40,
            oldPrice: 40,
            abbr: 'AR',
            sku: 'cheese_burger',
        }, {
            title: 'Donner Meat',
            desc: 'Prepared with onions, capsicums, garlic, fresh tomatoes and chef`s own selected spices',
            price: 3,
            oldPrice: 3,
            abbr: 'EN',
            sku: 'donner_meat',
        }, {
            title: 'دونر لحم',
            desc: 'محضرة من البصل والفليفلة والثوم والطماطم الطازجة والبهارات الخاصة',
            price: 6,
            oldPrice: 6,
            abbr: 'AR',
            sku: 'donner_meat',
        }, {
            title: 'Chicken Wrap',
            desc: 'Sliced grilled chicken breast, nestled in a fresh mix of Green Leaf lettuce with shredded',
            price: 3,
            oldPrice: 3,
            abbr: 'EN',
            sku: 'chicken_wrap',
        }, {
            title: 'راب الدجاج',
            desc: 'شرائح صدر دجاج مشوي ، متبل بمزيج طازج من الخس الأخضر مع قطع مقطع',
            price: 6,
            oldPrice: 6,
            abbr: 'AR',
            sku: 'chicken_wrap',
        }, {
            title: '1 Piece Of Chicken Meal',
            desc: 'Salad topped reviewer Kelly\'s expectations for a chicken salad',
            price: 2.5,
            oldPrice: 2.5,
            abbr: 'EN',
            sku: '1_piece_of_chicken_meal',
        }, {
            title: 'وجبة قطعة دجاج',
            desc: 'تصدرت السلطة توقعات المراجع كيلي لسلطة الدجاج',
            price: 5,
            oldPrice: 5,
            abbr: 'AR',
            sku: '1_piece_of_chicken_meal',
        },
    ]
}