module.exports = {
    usersSeed: [
        {
            username: 'root',
            email: 'root@tdev.app',
            password: 'password',
            firstName: 'Root',
            lastName: 'Account',
            role: 'root',
            phone: '13130545621',
            picture: '/assets/images/dashboard/man.jpg',
            ipAddress: '',
            loginCount: 0,
            token: '',
        },
        {
            username: 'admin',
            email: 'admin@tdev.app',
            password: 'password',
            firstName: 'Admin',
            lastName: 'Account',
            role: 'admin',
            phone: '13130545622',
            picture: '/assets/images/dashboard/man.jpg',
            ipAddress: '',
            loginCount: 0,
            token: '',
        },
        {
            username: 'guest',
            email: 'guest@tdev.app',
            password: 'password',
            firstName: 'Guest',
            lastName: 'Account',
            role: 'guest',
            phone: '123456798',
            picture: '/assets/images/dashboard/man.jpg',
            ipAddress: '',
            loginCount: 0,
            token: '',
        },
        {
            username: 'user',
            email: 'user@tdev.app',
            password: 'password',
            firstName: 'User',
            lastName: 'Account',
            role: 'user',
            phone: '13130545623',
            picture: '/assets/images/dashboard/man.jpg',
            ipAddress: '',
            loginCount: 0,
            token: '',
        }
    ]
}