export const ar = {
    menu: {
        home: 'الصفحة الرئيسية',
        foods: 'الأطعمة',
        food: 'طعام',
        bag: 'كيس',
        search: 'بحث',
        your_bag: 'حقيبتك',
        check_out_info: 'معلومات الخروج',
        check_out_result: 'نتيجة الخروج',
        order_history: 'تاريخ الطلب',
        profile: 'الملف الشخصي',
        profile_general: 'الملف الشخصي العام',
        profile_address: 'عنوان ملف التعريف',
        shipping_address: 'عنوان الشحن',
        cards: 'البطاقات',
        order_detail: 'تفاصيل الطلب',
        order_track: 'تتبع الطلب',
        contact_us: 'اتصل بنا',
        sign_in: 'تسجيل الدخول',
        sign_out: 'خروج',
        about_us: 'معلومات عنا',
        policy: 'سياسات',
    },
    auth: {
        logo: 'أنفاس الطيب',
        food_shop: 'متجر المواد الغذائية',
        enter_as_guest: 'أدخل كضيف',
        login: 'تسجيل الدخول',
        sign_up: 'سجل',
        click_here: 'انقر هنا',
        dont_have_account: 'لا تملك حساب؟',
        email_is_not_verified: 'لم يتم التحقق من البريد الإلكتروني. لم تتلق رسالة التحقق؟',
        email_address: 'عنوان البريد الالكترونى',
        password: 'كلمه السر',
        submit: 'إرسال',
        username: 'اسم المستخدم',
        phone: 'هاتف',
        already_have_account: 'لديك حساب بالفعل؟',
        service_and_policy: 'بالتسجيل فإنك تقبل شروط الخدمة وسياسة الخصوصية.',
        verify_email: 'التحقق من البريد الإلكتروني',
        we_are_verifying: 'نحن نتحقق من عنوان بريدك الإلكتروني',
        go_to_signin: 'انتقل إلى صفحة تسجيل الدخول',
        sign_in: 'تسجيل الدخول',
        email_verified: 'تم التحقق من البريد الإلكتروني بنجاح',
        reset_password: 'اعد ضبط كلمه السر',
        reset_successfully: 'تم إعادة تعيين كلمة المرور الخاصة بك بنجاح',
        resend_verification_email: 'إعادة ارسال بريد التحقق',
        send_pw_reset_email: 'إرسال البريد الإلكتروني إعادة تعيين كلمة المرور',
    },
    home: {
        most_popular: 'الأكثر شعبية',
        categories: 'التصنيفات',
        order_now: 'اطلب الان',
    },
    category: {

    },
    food: {
        quantity: 'كمية',
        other_description: 'وصف آخر',
        add_to_bag: 'أضف الى الحقيبة',
        description: 'وصف',
        comment_now: 'يرجى التعليق الآن',
        subject: 'موضوع',
        rating: 'تقييم',
        cancel: 'إلغاء',
        submit: 'إرسال',
        book: 'كتاب',
        comment: 'تعليق',
    },
    bag: {
        notes: 'ملاحظات',
        items: 'العناصر',
        total_cost: 'التكلفة الإجمالية',
        total: 'مجموع',
        check_out: 'الدفع',
    },
    profile: {
        none: 'لا يوجد',
        add_address: 'اضف عنوان',
        name: 'اسم',
        country: 'بلد',
        state: 'حالة',
        city: 'مدينة',
        address: 'عنوان',
        cancel: 'إلغاء',
        submit: 'إرسال',
        no_address: 'لا توجد عناوين. يرجى إضافة عنوان جديد.',
        shipping_address: 'عنوان الشحن',
        new_address: 'العنوان الجديد',
        expire: 'تنقضي',
        holder_name: 'اسم صاحب التسجيل',
        no_card: 'لا توجد بطاقات. يرجى إضافة بطاقة جديدة.',
        cards: 'البطاقات',
        new_card: 'بطاقة جديدة',
        add_card: 'إضافة بطاقة',
        card_type: 'نوع البطاقة',
        card_number: 'رقم البطاقة',
        expire_date: 'تاريخ انتهاء الصلاحية',
        cvv: 'CVV',
        update_card: 'تحديث البطاقه',
        update_address: 'تحديث العنوان',
        edit_profile: 'تعديل الملف الشخصي',
        order_history: 'تاريخ الطلب',
        log_out: 'تسجيل خروج',
        no_orders: 'لا توجد أوامر.',
        delivery_style: 'أسلوب التسليم',
        save: 'حفظ',
    },
    order: {
        order_detail: 'تفاصيل الطلب',
        order_information: 'معلومات الطلب',
        track_order: 'ترتيب المسار',
        order_status: 'حالة الطلب',
        created_at: 'أنشئت في',
        price: 'السعر',
        status: 'الحالة',
        pending: 'طلب معلق',
        confirm: 'أكد الطلب',
        processing: 'معالجة الطلب',
        delivery: 'أمر التسليم',
        readyreceipt: 'إيصال جاهز',
        delivered: 'تم التوصيل',
    },
    checkout: {
        your_order: 'طلبك',
        contact_info: 'معلومات الاتصال',
        first_name: 'الاسم الاول',
        last_name: 'الكنية',
        phone: 'هاتف',
        email: 'البريد الإلكتروني',
        address: 'عنوان',
        payment_info: 'معلومات الدفع',
        cardholder_name: 'إسم صاحب البطاقة',
        card_number: 'رقم البطاقة',
        card_expiration: 'انتهاء بطاقة',
        cvv: 'CVV',
        check_out: 'الدفع',
        date: 'تاريخ',
        total_bill: 'إجمالي الفاتورة',
        style_of_delivery: 'أسلوب التسليم',
        now: 'الآن',
        pickup: 'امسك',
        later: 'في وقت لاحق',
        branch: 'فرع شجرة',
        delivery_time: 'موعد التسليم',
        confirm: 'تؤكد',
        back: 'عودة',
        edit: 'تعديل',
        name: 'اسم',
        phone_number: 'رقم الهاتف',
        change_address: 'تغيير العنوان',
        no_cards: 'لا توجد بطاقات.',
        confirm_payment: 'ستحتاج إلى تأكيد الدفع',
        expiration_date: 'تاريخ الإنتهاء',
        home: 'الصفحة الرئيسية',
        try_again: 'حاول مجددا',
        confirm_success: 'تأكيدك ناجح',
        confirm_unsuccess: 'تأكيدك غير ناجح'
    },
    common: {
        about_us: 'معلومات عنا',
        contact_us: 'اتصل بنا',
        policy: 'سياسات',
    }
}