export const en = {
    menu: {
        home: 'Home',
        foods: 'Foods',
        food: 'Food',
        bag: 'Bag',
        search: 'Search',
        your_bag: 'Your Bag',
        check_out_info: 'Checkout Info',
        check_out_result: 'Checkout Result',
        order_history: 'Order History',
        profile: 'Profile',
        profile_general: 'General Profile',
        profile_address: 'Profile Address',
        shipping_address: 'Shipping Address',
        cards: 'Cards',
        order_detail: 'Order Detail',
        order_track: 'Order Track',
        contact_us: 'Contact Us',
        sign_in: 'Sign in',
        sign_out: 'Sign out',
        about_us: 'About Us',
        policy: 'Policy',
    },
    auth: {
        logo: 'Anfas Alteeb',
        food_shop: 'Food Shop',
        enter_as_guest: 'Enter as Guest',
        login: 'Login',
        sign_up: 'Sign up',
        click_here: 'Click here',
        dont_have_account: 'Don\'t have a account?',
        email_is_not_verified: 'Email is not verified. Have not received verification email?',
        email_address: 'Email Address',
        password: 'Password',
        submit: 'Submit',
        username: 'Username',
        phone: 'Phone',
        already_have_account: 'Already have a account?',
        service_and_policy: 'By signing up you accept the Terms of Service and Privacy Policy.',
        verify_email: 'Verify Email',
        we_are_verifying: 'We are verifying your email address',
        go_to_signin: 'Go to Sign In page',
        sign_in: 'Sign In',
        email_verified: 'Email has been verified successfully',
        reset_password: 'Reset Your Password',
        reset_successfully: 'Your password has been reset successfully',
        resend_verification_email: 'Resend Verification Email',
        send_pw_reset_email: 'Send Password Reset Email',
    },
    home: {
        most_popular: 'Most Popular',
        categories: 'Categories',
        order_now: 'ORDER NOW',
    },
    category: {

    },
    food: {
        quantity: 'Quantity',
        other_description: 'Other Description',
        add_to_bag: 'Add to bag',
        description: 'Description',
        comment_now: 'Please comment now',
        subject: 'Subject',
        rating: 'Rating',
        cancel: 'Cancel',
        submit: 'Submit',
        book: 'Book',
        comment: 'Comment',
    },
    bag: {
        notes: 'Notes',
        items: 'Items',
        total_cost: 'Total Cost',
        total: 'TOTAL',
        check_out: 'Check out',
    },
    profile: {
        none: 'None',
        add_address: 'Add Address',
        name: 'Name',
        country: 'Country',
        state: 'State',
        city: 'City',
        address: 'Address',
        cancel: 'Cancel',
        submit: 'Submit',
        no_address: 'There are no addresses. Please add new address.',
        shipping_address: 'Shipping Address',
        new_address: 'New Address',
        expire: 'Expire',
        holder_name: 'Holder Name',
        no_card: 'There are no cards. Please add new card.',
        cards: 'Cards',
        new_card: 'New Card',
        add_card: 'Add Card',
        card_type: 'Card Type',
        card_number: 'Card Number',
        expire_date: 'Expire Date',
        cvv: 'CVV',
        update_card: 'Update Card',
        update_address: 'Update Address',
        edit_profile: 'Edit Profile',
        order_history: 'Order History',
        log_out: 'Log Out',
        no_orders: 'There are no orders.',
        delivery_style: 'Delivery Style',
        save: 'Save',
    },
    order: {
        order_detail: 'Order Detail',
        order_information: 'Order Information',
        track_order: 'Track Order',
        order_status: 'Order Status',
        created_at: 'created at',
        price: 'Price',
        status: 'Status',
        pending: 'Pending Order',
        confirm: 'Confirm Order',
        processing: 'Processing Order',
        delivery: 'Delivery Order',
        readyreceipt: 'Ready Receipt',
        delivered: 'Delivered',
    },
    checkout: {
        your_order: 'Your Order',
        contact_info: 'Contact Info',
        first_name: 'First Name',
        last_name: 'Last Name',
        phone: 'Phone',
        email: 'Email',
        address: 'Address',
        payment_info: 'Payment Info',
        cardholder_name: 'Cardholder Name',
        card_number: 'Card Number',
        card_expiration: 'Card Expiration',
        cvv: 'CVV',
        check_out: 'CHECK OUT',
        date: 'Date',
        total_bill: 'Total Bill',
        style_of_delivery: 'Style of delivery',
        now: 'Now',
        pickup: 'Pickup',
        later: 'Later',
        branch: 'Branch',
        delivery_time: 'Delivery Time',
        confirm: 'Confirm',
        back: 'Back',
        edit: 'Edit',
        name: 'Name',
        phone_number: 'PHONE NUMBER',
        change_address: 'Change Address',
        no_cards: 'There are no cards.',
        confirm_payment: 'You will need to confirm the payment',
        expiration_date: 'Expiration Date',
        home: 'Home',
        try_again: 'Try Again',
        confirm_success: 'Your confirmation is successful',
        confirm_unsuccess: 'Your confirmation is unsuccessful'
    },
    common: {
        about_us: 'About Us',
        contact_us: 'Contact Us',
        policy: 'Policy',
    }
}